disabled_rules: # rule identifiers turned on by default to exclude from running
  - todo

opt_in_rules:
  - empty_count # Find all the available rules by running: `swiftlint rules`
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - literal_expression_end_indentation
  - operator_usage_whitespace
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
# - redundant_type_annotation
# - implicit_return

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Build
  - .build
  - Tests

identifier_name:
  excluded: # excluded via string array
    - ok
