os: osx
osx_image: xcode10.3
language: objective-c


matrix:
  include:
    # - env: XCODE_DESTINATION="platform=iOS Simulator,OS=10.3,name=iPhone 6s Plus"
    # - env: XCODE_DESTINATION="platform=iOS Simulator,OS=10.3,name=iPhone 7"
    - env: XCODE_DESTINATION="platform=iOS Simulator,OS=10.3,name=iPhone X"
    # - env: XCODE_DESTINATION="platform=iOS Simulator,OS=10.3,name=iPad Air 3"
    # - env: XCODE_DESTINATION="platform=iOS Simulator,OS=10.3,name=iPad Pro (12.9 inch)"
    # - env: XCODE_DESTINATION="platform=iOS Simulator,OS=10.3,name=iPad Retina"
    - os: linux
      dist: trusty
      language: generic


# BUG FIX: https://github.com/travis-ci/travis-ci/issues/6307
before_install: rvm get head


install: . ./scripts/install-swift.sh


script: ./scripts/run-tests.sh
